include: package:lint/analysis_options.yaml

linter:
  rules:
    # activate
    always_use_package_imports: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    lines_longer_than_80_chars: true
    sort_child_properties_last: true
    unawaited_futures: true
    unnecessary_const: true

    # deactivate
    ignore:
      prefer_const_constructors
