name: calorie_calculator
description: "Simple calorie calculator app"

publish_to: 'none'

version: 1.2.2
repository: https://github.com/DennisJacob128/calorie_calculator

environment:
  sdk: ^3.7.0

dependencies:
  age_calculator: ^1.0.0
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  test: ^1.25.15


flutter:
  uses-material-design: true

# App icons
flutter_launcher_icons:
  android: true
  image_path: assets/logo.png
  adaptive_icon_foreground: assets/logo.png
  adaptive_icon_background: '#83da85'

# Splash screen
flutter_native_splash:
  color: '#83da85'
  image: assets/logo.png # Under Android 12
  android_12:
    image: assets/logo.png   # Android 12 and higher
  android: true
  ios: true
