name: calorie_calculator
description: "Simple calorie calculator app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_test:
    sdk: flutter
  lint: ^2.8.0


flutter:
  uses-material-design: true

# App icons
flutter_launcher_icons:
  android: true
  image_path: assets/logo.png
  adaptive_icon_foreground: assets/logo.png
  adaptive_icon_background: '#83da85'

# Splash screen
flutter_native_splash:
  color: '#83da85'
  image: assets/logo.png # Under Android 12
  android_12:
    image: assets/logo.png   # Android 12 and higher
  android: true
  ios: true
